using System.Text;
using System.Text.Json;

namespace RudeAuth.Tests;

// The crypto is checked against known-answer vectors generated by the server's
// own cmd/rudeauth-vectors, so matching proves the SDK agrees with the server,
// not merely with itself.
public class CryptoTests
{
    private static JsonElement Vectors()
    {
        string path = Path.Combine(AppContext.BaseDirectory, "testdata", "vectors.json");
        return JsonDocument.Parse(File.ReadAllText(path)).RootElement;
    }

    private static byte[] FromHex(string s) => Convert.FromHexString(s);
    private static string ToHex(byte[] b) => Convert.ToHexString(b).ToLowerInvariant();

    [Fact]
    public void VerifyMatchesServerSignature()
    {
        JsonElement v = Vectors().GetProperty("ed25519");
        byte[] pub = FromHex(v.GetProperty("public_key_hex").GetString()!);
        string endpoint = v.GetProperty("endpoint").GetString()!;
        byte[] data = FromHex(v.GetProperty("data_hex").GetString()!);
        byte[] sig = FromHex(v.GetProperty("signature_hex").GetString()!);

        Assert.True(Crypto.Verify(pub, endpoint, data, sig), "rejected a real server signature");

        byte[] tampered = (byte[])data.Clone();
        tampered[0] ^= 0x01;
        Assert.False(Crypto.Verify(pub, endpoint, tampered, sig), "accepted tampered data");
        Assert.False(Crypto.Verify(pub, "variables", data, sig), "accepted a different endpoint");
    }

    [Fact]
    public void DeriveSessionKeyMatchesServer()
    {
        JsonElement root = Vectors();
        JsonElement x = root.GetProperty("x25519");
        JsonElement sk = root.GetProperty("session_key");

        byte[] got = Crypto.DeriveSessionKey(
            FromHex(x.GetProperty("private_a_hex").GetString()!),
            FromHex(x.GetProperty("public_b_hex").GetString()!),
            sk.GetProperty("session_id").GetString()!);

        Assert.Equal(sk.GetProperty("key_hex").GetString(), ToHex(got));
    }

    [Fact]
    public void OpenSealedMatchesServer()
    {
        JsonElement v = Vectors().GetProperty("xchacha20poly1305");
        byte[] key = FromHex(v.GetProperty("key_hex").GetString()!);
        byte[] sealedBlob = FromHex(v.GetProperty("sealed_hex").GetString()!);
        byte[] aad = Encoding.ASCII.GetBytes(v.GetProperty("aad").GetString()!);

        byte[]? plain = Crypto.OpenSealed(key, sealedBlob, aad);
        Assert.NotNull(plain);
        Assert.Equal(v.GetProperty("plaintext_hex").GetString(), ToHex(plain!));

        Assert.Null(Crypto.OpenSealed(key, sealedBlob, Encoding.ASCII.GetBytes("files:core.dll")));
    }
}
